version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: report-engine
    container_name: report-engine-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - report-engine
  db:
    image: mysql/mysql-server:8.0.27
    container_name: report-engine-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - report-engine

networks:
  report-engine:
    driver: bridge
