version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: report-engine
    container_name: report-engine-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - report-engine

networks:
  report-engine:
    driver: bridge
